name: check version code
description: >-
  Check whether current Git commit has a tag
  match the version code of current package.

inputs:
  manager:
    description: package manager name
    default: unknown
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: sh $GITHUB_ACTION_PATH/action.sh
      env:
        manager: ${{ inputs.manager }}
